version: '3'
services:
  tempbuild:
    image: kawagami77/api-server:axum
    ports:
      - "3000:3000"
    container_name: api-server-axum
    working_dir: /app
    volumes:
      - .env:/app/.env
  # database:
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_USER=kawa
  #     - POSTGRES_PASSWORD=kawa
  #     - POSTGRES_DB=kawa
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   volumes:
  #     - ../tempbuild/dbdata:/var/lib/postgresql/data
  #     # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"
