-- Baseline down：整庫重置（squash 後不支援部分回退，僅供本地開發重建）
DROP TABLE IF EXISTS
    public.admin_audit_logs,
    public.app_settings,
    public.blogs,
    public.chat_messages,
    public.daily_visitor_stats,
    public.firebase_images,
    public.hackmd_posts,
    public.hackmd_users,
    public.images,
    public.invoice_lottery_numbers,
    public.invoices,
    public.ledger_entries,
    public.logs,
    public.lotto_draws,
    public.lotto_tickets,
    public.member_oauth,
    public.members,
    public.permissions,
    public.portfolio,
    public.role_permissions,
    public.roles,
    public.stock_buyback_periods,
    public.stock_changes,
    public.stock_closing_prices,
    public.stock_day_all,
    public.stock_ex_rights,
    public.stock_ex_rights_checked,
    public.torrents,
    public.user_roles,
    public.users
CASCADE;
DROP FUNCTION IF EXISTS public.update_timestamp() CASCADE;
